server:
  port: 4000

spring:
  datasource:
    url: jdbc:h2:mem:restaurant_teamv_test?serverTimezone=Asia/Seoul;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=FALSE;
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        globally_quoted_identifiers: true
        jdbc:
          time_zone: Asia/Seoul
  data:
    redis:
      host: localhost
      port: 6379

  h2:
    console:
      enabled: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

security:
  jwt:
    token:
      secret-key: dGVhbXZfand0X3NlY3JldF9rZXlfdGVzdA==
      access:
        expire-length: 2592000000 #30일

openapi:
  base-url: https://openapi.gg.go.kr
  service-key: ${SERVICE_KEY}

schedules:
  cron:
    restaurant-collection: 0 0 2 * * *
    lunch-recommendation: 0 30 11 * * *

discord:
  bot: teamV
  webhook:
    url: ${WEBHOOK_TEST_URL}
    avatar_url: ${AVATAR_URL}
    author_url: ${AUTHOR_URL}
    author_icon: ${AUTHOR_ICON}
    footer_icon: ${FOOTER_ICON}